version: "3.8"

services:
  ticket:
    image: souni/ticket
    ports:
      - "8085:8085"
    networks:
      - ahmed-network
    depends_on:
      - db


    environment:
       SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/voyageAgency?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
       SPRING_DATASOURCE_USERNAME: root
       SPRING_DATASOURCE_PASSWORD: root
  db:
    image: mysql:8
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABA
db:
    image: mysql:8
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: pidev
    ports:
      - "3306:3306"
    networks:
      - ahmed-network
      
networks:
  ahmed-network: